name: temannakes
description: "Asisten Klinis Terintegrasi untuk Tenaga Kesehatan Profesional Indonesia. TemanNakes menghadirkan referensi obat komprehensif, kalkulator medis presisi tinggi, dan efisiensi manajemen data pasien dalam satu platform luring yang andal."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  google_mobile_ads: ^5.0.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  # Patient Form Module
  excel: ^4.0.6
  pdf: ^3.10.8
  printing: ^5.12.0
  open_file: ^3.3.2
  uuid: ^4.5.1
  # Smart Notification System
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk value

flutter:
  uses-material-design: true
  assets:
    - assets/database/temannakes.db
    - assets/images/logo.png
