import 'dart:io';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import '../domain/models/form_template.dart';
import '../domain/models/patient_record.dart';

class ExcelExporter {
  /// Export ke file .xlsx dan kembalikan path-nya
  static Future<String> export({
    required FormTemplate template,
    required List<PatientRecord> records,
  }) async {
    final excel = Excel.createExcel();
    final sheetName = template.name.replaceAll(RegExp(r'[^\w ]'), '');
    final sheet = excel[sheetName];

    // ── Header row styling ──────────────────────────────────────────────────
    final headerStyle = CellStyle(
      bold: true,
      backgroundColorHex: ExcelColor.fromHexString('#1B5E20'),
      fontColorHex: ExcelColor.fromHexString('#FFFFFF'),
      horizontalAlign: HorizontalAlign.Center,
    );

    // Column: No, Tanggal Input, then each field
    final headers = <String>[
      'No',
      'Tanggal Input',
      ...template.fields.map((f) => f.label),
    ];

    for (var col = 0; col < headers.length; col++) {
      final cell = sheet.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: 0));
      cell.value = TextCellValue(headers[col]);
      cell.cellStyle = headerStyle;
    }

    // ── Data rows ───────────────────────────────────────────────────────────
    final dateStyle = CellStyle(
      horizontalAlign: HorizontalAlign.Center,
    );

    for (var i = 0; i < records.length; i++) {
      final record = records[i];
      final rowIndex = i + 1;

      // No
      sheet
          .cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: rowIndex))
          .value = IntCellValue(i + 1);

      // Tanggal Input
      final dateCell = sheet.cell(
          CellIndex.indexByColumnRow(columnIndex: 1, rowIndex: rowIndex));
      final d = record.createdAt;
      dateCell.value = TextCellValue(
          '${d.day.toString().padLeft(2, '0')}-${d.month.toString().padLeft(2, '0')}-${d.year}');
      dateCell.cellStyle = dateStyle;

      // Field values
      for (var col = 0; col < template.fields.length; col++) {
        final field = template.fields[col];
        final cell = sheet.cell(
            CellIndex.indexByColumnRow(columnIndex: col + 2, rowIndex: rowIndex));
        final value = record.displayValue(field.id);
        cell.value = TextCellValue(value);
      }
    }

    // ── Footer Branding row ──────────────────────────────────────────────────
    final footerStyle = CellStyle(
      italic: true,
      fontColorHex: ExcelColor.fromHexString('#9E9E9E'),
    );
    final footerRowIndex = records.length + 2;
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: footerRowIndex)).value = 
        TextCellValue('Generated by TemanNakes Pinnacle V2.0 — Institutional Data Integrity Verified');
    sheet.cell(CellIndex.indexByColumnRow(columnIndex: 0, rowIndex: footerRowIndex)).cellStyle = footerStyle;

    // ── Auto-width approximation ─────────────────────────────────────────────
    sheet.setColumnWidth(0, 6.0); // No
    sheet.setColumnWidth(1, 18.0); // Tanggal
    for (var col = 0; col < template.fields.length; col++) {
      final label = template.fields[col].label;
      sheet.setColumnWidth(col + 2, (label.length * 1.2 + 12).clamp(14.0, 40.0));
    }

    // ── Save file ────────────────────────────────────────────────────────────
    final dir = await getApplicationDocumentsDirectory();
    final safeName = template.name.replaceAll(RegExp(r'[^\w]'), '_');
    final filename = '${safeName}_${DateTime.now().millisecondsSinceEpoch}.xlsx';
    final file = File('${dir.path}/$filename');
    final bytes = excel.save();
    if (bytes == null) throw Exception('Gagal generate file Excel.');
    await file.writeAsBytes(bytes);
    return file.path;
  }
}
